apiVersion: v1
kind: Service
metadata:
  name: my-mongo-node-app-service
  selector:
    app: my-mongo-node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort
